import Head from "next/head";

import { api } from "../lib/api";
import { Banner } from "../components/Banner";
import { Header } from "../components/Header";
import { SliderSection } from "../components/Slider";
import { TravelTypes } from "../components/TravelTypes";
import { GetStaticProps } from "next";
import { Continents, ITravelTypes } from "../shared/types";
import { travelTypesData } from "../lib/api/travelTypesData";
import { Box } from "@chakra-ui/react";

export default function Home({
  continents,
  travelTypesData,
}: {
  continents: Continents[];
  travelTypesData: ITravelTypes[];
}) {
  return (
    <Box minH="100vh" maxW="100vw">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner img="/images/banner.jpg" homeBanner={true} />
      <TravelTypes data={travelTypesData} />
      <SliderSection continents={continents} />
    </Box>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const { data: continents } = await api.get("continents");

  return {
    props: {
      continents,
      travelTypesData,
    },
    revalidate: 60 * 60 * 24,
  };
};
